language: R
# addons:
#   apt:
#     packages:
#     - pandoc
#     - texlive-xetex
#     - texlive-plain-extra
#     - texlive-generic-recommended
#     - texlive-latex-recommended
#     - texlive-latex-extra
#     - texlive-fonts-recommended
#     - texlive-fonts-extra
#     - latex-xcolor
#     - dvipng
#     - lmodern
install: tlmgr install mdframed mweights needspace sourcecodepro sourcesanspro collection-fontsextra
script: |
  pandoc --verbose pandoc-metadata.yaml README.md [0-9]*.md -o hack-the-hackerspace.pdf --template eisvogel.tex --toc --listings --metadata date="`date +%D`" --include-before-body=include-cover.tex
  numpages=$(pdfinfo hack-the-hackerspace.pdf | awk '/^Pages/ { print $2}')
  pdfbook hack-the-hackerspace.pdf 2-$(($numpages-2)) -o hack-the-hackerspace-booklet-body.pdf
deploy:
  provider: releases
  api_key:
    secure: cIRIKuDWejK79Kojh2URkQBmQcKDJtH/MmrzgCySQ7ArjbZ6/cPkS014QbNmUft4GiRGZzIiulfkkvLtdT4UVGVXEw7gTK/V5b6bEci6fst4rDPL/hCDeXcLutOxcOwb7vei38V5XhE+1D2UcFQFNJFkeo60WKWR9ybIQ7pAemo=
  file:
    - hack-the-hackerspace.pdf
    - hack-the-hackerspace-booklet-cover.pdf
    - hack-the-hackerspace-booklet-body.pdf
  skip_cleanup: true
  on:
    repo: "0x20/HTH"
if:
  tag IS blank